services:
  web:
    build: .
    command: bash -c 'pnpm install && pnpm run dev --host'
    # command: bash -c 'pnpm install && pnpm run build && pnpm run preview --host'
    ports:
      - "5173:5173"
      # - '4173:4173'
    working_dir: "/preload_data_example"
    expose:
      - "5173"
      # - '4173'
    volumes:
      - ".:/preload_data_example"
      - node_modules:/preload_data_example/node_modules
      - pnpm-store:/preload_data_example/.pnpm-store
      - svelte-kit:/preload_data_example/.svelte-kit
    environment:
      - VITE_ENVIRONMENT=development
      - DO_NOT_TRACK=1
    # env_file:
    #   - .env
  # sanity:
  #   build: .
  #   command: bash -c 'pnpm install && pnpm run dev --host --port 3333'
  #   ports:
  #     - "3333:3333"
  #     - "4321:4321"
  #   working_dir: "/sanity"
  #   expose:
  #     - "3333"
  #     - "4321"
  #   volumes:
  #     - "./sanity:/sanity"
  #     - "sanity_node_modules:/sanity/node_modules"
  #     - "sanity_pnpm-store:/sanity/.pnpm-store"
  #     - "sanity:/sanity/.sanity"
  #   env_file:
  #     - sanity/.env
volumes:
  node_modules:
  pnpm-store:
  svelte-kit:
  sanity_node_modules:
  sanity_pnpm-store:
  sanity:
